import 'recyclable.dart';

String _stringRecycle = 'can be recycled';
String _stringNonRecycle = 'cannot be recycled';
String _stringDonate = 'can be donated';
String _stringNonDonate = 'cannot be donated';

/* Denton Recycling Center Notes */
String _instStoreDropOff =
    'Please drop-off this item at a store drop-off site.';
//TODO: https://www.plasticfilmrecycling.org/recycling-bags-and-wraps/find-drop-off-location/
String _instRecyclable =
    'Please place this item in your blue recycling cart or recycling dumpster. Please make sure items are empty, clean, dry, and loose (no plastic bags).';
String _instHouseholdHazardWaste =
    'Please drop-off at this item at the listed location for safe disposal. Proof of residency required.';
String _instHouseholdBulkyWaste =
    'Household bulky items collection must be scheduled, call customer service at least one business day prior to collection day at 940 349-8700 to schedule. Residents can have up to two large household items picked up weekly at no charge. Additional items can be scheduled for a fee. Construction and remodel materials are not included in household bulky item collection. ';
String _instTrash = 'Put this item in your trash can.';
String _instAppliances =
    'Please drop-off this item at the listed locations. Fees may apply.';
String _instElectronicWaste =
    'Please drop-off this item at the listed locations for safe disposal. Fees may apply. For more details on electronics recycling please visit: https://www.tceq.texas.gov/p2/recycle/electronics';
//TODO: Christmas Tree Description
String _instBrushCollection =
    'Call customer service at 940-349-8700 to schedule a brush collection*. Brush includes limbs, branches, brush, etc. Four cubic yards of brush can be collected weekly, fees will apply for any amount over 4 cubic yards. Please make sure all brush is cut into 6 ft lengths.    *Customers opted into yard waste service will not need to call and schedule amounts under 4 cubic yards.';
//TODO: https://www.cityofdenton.com/en-us/all-departments/utilities/solid-waste-and-recycling/recycling-program#!rc-cpage=476161
String _instNote =
    'Important message regarding COVID-19: Due to ongoing changes to prevent the spread of COVID-19, some locations and services may have temporarily closed or modified operations. Please call before driving.';

//TODO: complete the array

//TODO: 사실은, class 넣고 해야하는데.. .근데 지금까지 coding한거랑 안망자서 ㅜ 그냥 일단 하자.

int _recyclableNumber = 0;

List<Recyclable> recyclable = [
  //default
  Recyclable(
    title: '',
    description: '',
    recycle: '',
    recycleDesc: '',
    instruction: '',
    specialFacility: '',
    recyclingPreparation: '',
    recyclingProcess: '',
    alternativeOptions: '',
    why: '',
    donate: '',
    creativeUse: '',
  ),
  Recyclable(
    title: 'AEROSOL CAN',
    description: '(EMPTY)',
    recycle: _stringRecycle,
    recycleDesc: _instRecyclable,
    instruction: '',
    specialFacility: '',
    recyclingPreparation:
        'Do your best to use up all the product inside. If the can still has product inside, even if it’s nonhazardous product like whipped cream, your recycling program will not accept it. The easiest way to make sure it’s empty is to shake the can and listen for liquid inside, or spray until nothing comes out. \n\nMost aerosol cans come with a plastic cap, which should be removed and recycled separately. Visit our recycling guide on plastic caps for more information.\n\nDO NOT puncture a hole in the can to remove any remaining product, as the can will explode and hurt you. You should also not attempt to remove the spray nozzle on top of the can.\n\nVerify whether your community accepts aerosol cans with other metal cans, or whether they are classified as household hazardous waste (HHW). There are separate disposal options for each. (Source: Earth911)',
    recyclingProcess:
        'The process for recycling full aerosol cans is simple. Using special equipment, a worker punches a hole in the can and allows any remaining liquid to drain out. The liquid is kept in a secure container so it can be disposed of properly. The empty metal can is sent to a metal recycler. (Source: RecycleNation)',
    alternativeOptions: '',
    why:
        'Aerosol cans are made of highly recyclable steel, similar to a can of Campbell\u0027s soup with one important difference. Aerosol cans\u0027 contents are under pressure. That\u0027s where recycling them gets tricky. Aerosol cans need to be completely empty to be sent safely through the recycling process because pressurized gas can explode if crushed during transport or at the sorting facility. Aerosol gasses are flammable as well so be sure to use up all the contents before recycling. (Source: RecycleByCity)',
    donate: _stringNonDonate,
    creativeUse: 'PINTEREST IDEAS',
  ),
//  Recyclable(
//      'AEROSOL CAN', '(FULL OR PARTIALLY FULL)', instHouseholdHazardWaste, ''),
//  Recyclable('ANIMAL BEDDING', '', instTrash, ''),
//  Recyclable('ANTIFREEZE', '', instHouseholdHazardWaste, ''),
//  Recyclable('ASEPTIC CARTON', '', instRecyclable, ''),
//  Recyclable('BACKPACK', '', instTrash, ''),
//  Recyclable('BAG', '(PLASTIC)', instStoreDropOff, ''),
//  Recyclable('BAKED GOODS', '', instTrash, ''),
//  Recyclable('BAKING TRAY', '', instTrash, ''),
//  Recyclable('BALL', '', instTrash, ''),
//  Recyclable('BALLOON', '', instTrash, ''),
//  Recyclable('BARBEQUE GRILL', '', instHouseholdBulkyWaste, ''),
//  Recyclable('BARBEQUE', '', instTrash, ''),
//  Recyclable('BASKETBALL HOOP', '', instHouseholdBulkyWaste, ''),
//  Recyclable('BATTERY', '(DISPOSABLE)', instHouseholdHazardWaste, ''),
//  Recyclable('BATTERY', '(RECHARGEABLE)', instHouseholdHazardWaste, ''),
//  Recyclable('BED FRAME', '', instHouseholdBulkyWaste, ''),
//  //TODO: a.k.a. SODA BOTTLE
//  Recyclable('BEVERAGE BOTTLE', '(GLASS)', instRecyclable, ''),
//  Recyclable('BEVERAGE BOTTLE', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('BEVERAGE CAN', '(ALUMINUM)', instRecyclable, ''),
//  Recyclable('BICYCLE', '', instHouseholdBulkyWaste, ''),
//  Recyclable('BINDER', '', instTrash, ''),
//  Recyclable('BLANKET', '', instTrash, ''),
//  Recyclable('BLEACH', '', instHouseholdHazardWaste, ''),
//  Recyclable('BLINDS', '', instHouseholdBulkyWaste, ''),
//  //TODO: double check books.
//  Recyclable('BOOK', '(HARD COVER)', instRecyclable, ''),
//  Recyclable('BOOK', '(SOFT COVER)', instRecyclable, ''),
//  Recyclable('BOOKSHELF', '', instHouseholdBulkyWaste, ''),
//  Recyclable('BOTTLE', '(CERAMIC)', instTrash, ''),
//  Recyclable('BOTTLE', '(GLASS)', instRecyclable, ''),
//  Recyclable('BOTTLE', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('BOTTLE CAP', '(PLASTIC)', instTrash, ''),
//  Recyclable('BOX', '(CARDBOARD)', instRecyclable, ''),
//  Recyclable('BREAD', '', instTrash, ''),
//  Recyclable('BRUSH', '', instTrash, ''),
//  Recyclable('BUBBLE WRAP', '', instStoreDropOff, ''),
//  Recyclable('BUTANE FUEL', '', instHouseholdHazardWaste, ''),
//  Recyclable('CACTUS', '', instTrash, ''),
//  Recyclable('CALCULATOR', '', instTrash, ''),
//  Recyclable('CAMERA', '', instElectronicWaste, ''),
//  Recyclable('CANDLE JARS', '', instTrash, ''),
//  Recyclable('CANDY WRAPPERS', '', instTrash, ''),
//  Recyclable('CANDY', '', instTrash, ''),
//  Recyclable('CARDBOARD', '', instRecyclable, ''),
//  Recyclable('CAT TOWER', '', instHouseholdBulkyWaste, ''),
//  Recyclable('CD DISC', '', instTrash, ''),
//  Recyclable('CEILING FAN', '', instHouseholdBulkyWaste, ''),
//  Recyclable('CELLPHONE', '', instElectronicWaste, ''),
//  Recyclable('CERAMICS', '(BROKEN)', instTrash, ''),
//  Recyclable('CERAMICS', '', instTrash, ''),
//  Recyclable('CEREAL BOX LINERS', '', instTrash, ''),
//  Recyclable('CEREAL', '', instTrash, ''),
//  Recyclable('CHAIR', '', instHouseholdBulkyWaste, ''),
//  Recyclable(
//      'CHARGER',
//      '',
//      instElectronicWaste +
//          'Alternatively, you can drop it by local stores to recycle.',
//      ''),
//  Recyclable('CHEESE', '', instTrash, ''),
//  Recyclable('CHICKEN', '(INCLUDING BONES)', instTrash, ''),
//  Recyclable('CHIP BAG', '', instTrash, ''),
//  Recyclable('CHRISTMAS DECORATIONS', '', instTrash, ''),
//  Recyclable('CHRISTMAS TREE', '(ARTIFICIAL)', instHouseholdBulkyWaste, ''),
//  Recyclable('CHRISTMAS TREE', '(NATURAL)', instBrushCollection, ''),
//  Recyclable('CLOTHES', '', instTrash, ''),
//  Recyclable('COFFEE FILTERS', '', instTrash, ''),
//  Recyclable('COFFEE GROUNDS', '', instTrash, ''),
//  Recyclable('COFFEE MACHINE', '', instElectronicWaste, ''),
//  Recyclable('COLD PACK', '', instTrash, ''),
//  Recyclable('COMPUTER PERIPHERALS', '', instTrash, ''),
//
//  Recyclable('COOKIE TIN', '', instTrash, ''),
//  Recyclable('COOKING OIL', '', instHouseholdHazardWaste, ''),
//  Recyclable('COOKING POT', '(ALUMINUM)', '', '', '', ''),
//  Recyclable('COOKING POT', '(CERAMIC)', instTrash, ''),
//  Recyclable('COOKING POT', '(FIBERGLASS)', instTrash, ''),
//  Recyclable('COOKING POT', '(GLASS)', '', '', '', ''),
//  Recyclable('CORRUGATED CARDBOARD', '', instRecyclable, ''),
//  Recyclable('COSMETICS', '', instTrash, ''),
//  Recyclable('COTTON BALL', '', instTrash, ''),
//  Recyclable('COTTON PAD', '', instTrash, ''),
//  Recyclable('COTTON SWAB', '', instTrash, ''),
//  Recyclable('CUP', '(CERAMIC)', instTrash, ''),
//  Recyclable('CUP', '(GLASS)', instRecyclable, ''),
//  Recyclable('CUP', '(PAPER)', instRecyclable, ''),
//  Recyclable('CUP', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('CUP', '(STYROFOAM)', instTrash, ''),
//  Recyclable('CUP LID', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('CUTLERY', '(PLASTIC)', instTrash, ''),
//  Recyclable('CUTLERY', '(WOOD)', instTrash, ''),
//  Recyclable('DAIRY PRODUCTS', '', instTrash, ''),
//  Recyclable('DESK', '', instHouseholdBulkyWaste, ''),
//  Recyclable('DESKTOP COMPUTER', '', instElectronicWaste, ''),
//  Recyclable('DETERGENT BOTTLE', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('DISH SCRUB', '', instTrash, ''),
//  Recyclable('DOG FOOD BAG', '', instTrash, ''),
//  Recyclable('DOG KENNEL', '', instHouseholdBulkyWaste, ''),
//  Recyclable('DRYER LINT', '', instTrash, ''),
//  Recyclable('DRYER SHEET', '', instTrash, ''),
//  Recyclable('DUMBELL', '', '', '', '', ''),
//  Recyclable('DVD PLAYER', '', instElectronicWaste, ''),
//  Recyclable('EARPHONES', '', '', '', '', ''),
//  Recyclable('EGG CARTON', '(PAPER)', instRecyclable, ''),
//  //TODO: add a photo
//  Recyclable('EGG CARTON', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('EGG CARTON', '(STYROFOAM)', instTrash, ''),
//  Recyclable('EGG SHELL', '', instTrash, ''),
//  Recyclable('EGG', '', instTrash, ''),
//  Recyclable('ELECTRONICS', '', instElectronicWaste, ''),
//  Recyclable('ENVELOPE', '(PADDED)', instTrash, ''),
//  Recyclable('ENVELOPE', '(WITH PLASTIC WINDOW)', instRecyclable, ''),
//  Recyclable('ENVELOPE', '', instRecyclable, ''),
//  Recyclable('ERASER', '', instTrash, ''),
//  Recyclable('E-READER', '', instElectronicWaste, ''),
//  Recyclable('EXERCISE EQUIPMENT', '', instHouseholdBulkyWaste, ''),
//  Recyclable('FABRIC SOFTENER', '', instTrash, ''),
//  Recyclable('FACIAL TISSUES', '', instTrash, ''),
//  Recyclable('FIGURINES', '', instTrash, ''),
//  Recyclable('FILE CABINET', '', instHouseholdBulkyWaste, ''),
//  Recyclable('FIRE EXTINGUISHER', '', instHouseholdHazardWaste, ''),
//  Recyclable('FISH', '(INCLUDING BONES)', instTrash, ''),
//  Recyclable('FLOSS', '', instTrash, ''),
//  Recyclable('FLUORESCENT BULB', '(CFL)', instHouseholdHazardWaste, ''),
//  Recyclable('FLYERS', '(LAMINATED)', instTrash, ''),
//  Recyclable('FLYERS', '(NON-LAMINATED)', instRecyclable, ''),
//  Recyclable('FOAM', '(POLYSTYRENE)', instTrash, ''),
//  Recyclable('FOIL', '(ALUMINUM)', instTrash, ''),
//  Recyclable('FOLDER', '', instRecyclable, ''),
//  Recyclable('FOOD CAN', '(METAL)', instRecyclable, ''),
//  Recyclable('FOOD SCRAPS', '', instTrash, ''),
//  Recyclable('FRUIT', '', instTrash, ''),
//  Recyclable('FRYING PAN', '', '', '', '', ''),
//  Recyclable('FURNITURE', '', instHouseholdBulkyWaste, ''),
//  Recyclable('GLASS', '(BROKEN)', instTrash, ''),
//  Recyclable('GLASSES', '', '', '', '', ''),
//  Recyclable('GRAINS', '', instTrash, ''),
//  Recyclable('HAIR DRYER', '', '', '', '', ''),
//  Recyclable('HAIRBRUSH', '', instTrash, ''),
//  Recyclable('HANGER', '(METAL)', instTrash, ''),
//  Recyclable('HANGER', '(PLASTIC)', instTrash, ''),
//  Recyclable('HANGER', '(WOOD)', instTrash, ''),
//  Recyclable('HOME HEALTHCARE WASTE', '', instTrash, ''),
//  Recyclable('HOUSEHOLD CLEANER', '', instHouseholdHazardWaste, ''),
//  Recyclable('HUMAN HAIR', '', instTrash, ''),
//  Recyclable('ICE CREAM CARTON', '(PAPER)', instRecyclable, ''),
//  Recyclable('ICE CREAM CARTON', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('ICE CREAM CARTON', '(STYROFOAM)', instTrash, ''),
//  Recyclable('INK CARTRIDGE', '', instTrash, ''),
//  Recyclable('IRONING BOARD', '', instHouseholdBulkyWaste, ''),
//  Recyclable('JAR', '(CERAMIC)', instTrash, ''),
//  Recyclable('JAR', '(GLASS)', instRecyclable, ''),
//  Recyclable('JAR', '(PLASTIC)', '', '', '', ''),
//  Recyclable('JUICE BOX', '', instRecyclable, ''),
//  Recyclable('JUICE OR DRINKING POUCH', '', instTrash, ''),
//  Recyclable('KITCHEN KNIVES', '', instTrash, ''),
//  Recyclable('LAMP', '', instHouseholdBulkyWaste, ''),
//  Recyclable('LAPTOP', '', instElectronicWaste, ''),
//  Recyclable('LIGHT BULB', '(NOT CFL)', instHouseholdHazardWaste, ''),
//  Recyclable('MAGAZINE', '', instRecyclable, ''),
//  Recyclable('MAKE-UP SPONGE', '', instTrash, ''),
//  Recyclable('MASK', '', instTrash, ''),
//  Recyclable('MATTRESS COVERS', '', instTrash, ''),
//  Recyclable('MATTRESS', '', instHouseholdBulkyWaste, ''),
//  Recyclable('MEAT', '(INCLUDING BONES)', instTrash, ''),
//  Recyclable('MEDICAL WASTE', '', instTrash, ''),
//  Recyclable(
//      'MEDICINE',
//      '(PRESCRIPTION & OVER-THE-COUNTER)',
//      'For safe disposal, contact your local pharmacy for pharmaceutical drop-off information. Do not pour medications down the sink or flush down the toilet.',
//      ''),
//  Recyclable('METAL CAPS', '(FROM GLASS JARS)', instTrash, ''),
//  Recyclable('MICROWAVE', '', instHouseholdBulkyWaste, ''),
//  Recyclable('MILK JUG', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('MIRROR', '', instHouseholdBulkyWaste, ''),
//  Recyclable('MONITOR', '', instElectronicWaste, ''),
//  Recyclable('NAIL CLIPPER', '', instTrash, ''),
//  Recyclable('NAIL POLISH', '', instTrash, ''),
//  Recyclable('NEWSPAPER', '', instRecyclable, ''),
//  Recyclable('NUT & SHELL', '', instTrash, ''),
//  Recyclable('PAINT (LATEX)', '', instHouseholdHazardWaste, ''),
//  Recyclable('PAINT (OIL)', '', instHouseholdHazardWaste, ''),
//  Recyclable('PALLETS', '', instTrash, ''),
//  Recyclable('PAPER', '(LAMINATED)', instTrash, ''),
//  Recyclable('PAPER', '(NON-LAMINATED)', instRecyclable, ''),
//  Recyclable('PAPER', '(SHREDDED)', instRecyclable, ''),
//  Recyclable('PAPER CLIPS', '', instTrash, ''),
//  Recyclable('PAPER NAPKINS', '', instTrash, ''),
//  Recyclable('PAPER SHREDDER', '', instTrash, ''),
//  Recyclable('PAPER TOWEL', '', instTrash, ''),
//  Recyclable('PAPER TOWEL ROLL', '', instRecyclable, ''),
//  Recyclable('PARCHMENT PAPER', '', instTrash, ''),
//  Recyclable('PASTA', '', instTrash, ''),
//  Recyclable('PEN', '', instTrash, ''),
//  Recyclable('PICTURE FRAME', '', instHouseholdBulkyWaste, ''),
//  Recyclable('PIE PLATE', '(ALUMINUM)', instRecyclable, ''),
//  Recyclable('PILL BOTTLE', '(EMPTY)', instRecyclable, ''),
//  Recyclable('PILLOW', '', instTrash, ''),
//  Recyclable('PITCHER', '(CERAMIC)', instTrash, ''),
//  Recyclable('PITCHER', '(GLASS)', instRecyclable, ''),
//  Recyclable('PITCHER', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('PIZZA BOX', '(EMPTY, NO FOOD RESIDUE)', instRecyclable, ''),
//  Recyclable('PIZZA BOX', '(GREASY)', instTrash, ''),
//  Recyclable('PIZZA', '', instTrash, ''),
//  Recyclable('PLANT POTS', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('PLATE', '(CERAMIC)', instTrash, ''),
//  Recyclable('PLATE', '(GLASS)', instRecyclable, ''),
//  Recyclable('PLATE', '(PAPER)', instTrash, ''),
//  Recyclable('PLATE', '(PLASTIC)', instRecyclable, ''),
//  //TODO: ADD A PHOTO
//  Recyclable('PLATE', '(STYROFOAM)', instRecyclable, ''),
//  Recyclable('POPCORN BAG', '', instTrash, ''),
//  Recyclable('POPCORN', '', instTrash, ''),
//  Recyclable('POPSICLE STICK', '', instTrash, ''),
//  Recyclable('PRINTER', '', instElectronicWaste, ''),
//  Recyclable('PUMPKIN', '', instTrash, ''),
//  Recyclable('RACKET', '', instTrash, ''),
//  //TODO: 진짜 그런가? receipt이 recycle? 된다는데 careful instruction 필요.
//  Recyclable('RECEIPT', '', instRecyclable, ''),
//  //TODO: 다른 가전제품에도 appliances 들어가는지 확인 ㅜㅜ
//  Recyclable(
//      'REFRIGERATOR',
//      '',
//      instAppliances +
//          ' Additional fee applies for freon containing appliances.',
//      ''),
//  Recyclable('RIBBON & BOW', '', instTrash, ''),
//  Recyclable('RUG', '', instHouseholdBulkyWaste, ''),
//  Recyclable('SANITIZING WIPE', '', instTrash, ''),
//  Recyclable('SATELLITE DISH', '', instElectronicWaste, ''),
//  Recyclable('SAUCE BOTTLE', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('SAUCE & SYRUP', '', instTrash, ''),
//  Recyclable('SCISSORS', '', '', '', '', ''),
//  Recyclable('SHELLFISH', '', instTrash, ''),
//  Recyclable('SHOE BOX', '', instRecyclable, ''),
//  Recyclable('SHOE(S)', '', instTrash, ''),
//  Recyclable('SHUTTLECOCK', '', instTrash, ''),
//  Recyclable('SILVERWARE', '', instTrash, ''),
//  //TODO: trash랑 landfill이랑 뭐가 다르지?
//  Recyclable('SLEEPING BAG', '', instLandfill, ''),
//  //TODO: ADD A PHOTO
//  Recyclable('SIX PACK PLASTIC RINGS', '', instTrash, ''),
//  //TODO: 두 개나 있는데.. 일단 trash로 넣음
//  Recyclable('SMOKE DETECTOR', '', instTrash, ''),
//  Recyclable('SOAP BOTTLE', '(PLASTIC)', instRecyclable, ''),
//  //TODO: 정보 찾아보고 사진도.
//  Recyclable('SOAP BOX', '', '', '', ''),
//  Recyclable('STEEL', '', instTrash, ''),
//  Recyclable('STERNO', '', ???, ''),
//  Recyclable('STICKY NOTE', '', instRecyclable, ''),
//  Recyclable('STORAGE CONTAINER', '', '', '', '', ''),
//  Recyclable('STRAW', '(METAL)', instTrash, ''),
//  //TODO: 사진 없음.
//  Recyclable('STRAW', '(RUBBER)', ???, ''),
//  Recyclable('STRAW', '(PLASTIC)', instTrash, ''),
//  Recyclable('STRING & TWINE', '', instTrash, ''),
//  Recyclable('STYROFOAM', '', instTrash, ''),
//  Recyclable('SUITCASE', '', instHouseholdBulkyWaste, ''),
//  Recyclable('SUNSCREEN', '', instTrash, ''),
//  Recyclable('SURGE PROTECTOR', '', instElectronicWaste, ''),
//  Recyclable('TABLE FAN', '', instElectronicWaste, ''),
//  Recyclable('TABLE', '', instHouseholdBulkyWaste, ''),
//  Recyclable('TABLET', '', instElectronicWaste, ''),
//  Recyclable('TAKE-OUT CONTAINER', '', instTrash, ''),
//  Recyclable('TEABAG', '', instTrash, ''),
//  Recyclable('TELEVISION', '', instElectronicWaste, ''),
//  Recyclable('TEXTILE', '', instTrash, ''),
//  Recyclable(
//      'TIRE',
//      '',
//      'The City of Denton Landfill no longer accepts Rubber Tires. We recommend to take them to a Tire Retailer so it can be disposed of properly.',
//      ''),
//  Recyclable('TISSUE PAPER', '', instTrash, ''),
//  Recyclable('TOILET', '', instHouseholdBulkyWaste, ''),
//  Recyclable('TOILET PAPER ROLL', '', instRecyclable, ''),
//  Recyclable('TOILET PAPER', '', instTrash, ''),
//  Recyclable('TOOTHBRUSH', '(PLASTIC)', instTrash, ''),
//  Recyclable('TOOTHPICKS', '', instTrash, ''),
//  Recyclable('TOWEL', '', instTrash, ''),
//  Recyclable('TRAMPOLINE', '', instHouseholdBulkyWaste, ''),
//  Recyclable('TRASH CAN', '', instHouseholdBulkyWaste, ''),
//  Recyclable('TREADMILL', '', instHouseholdBulkyWaste, ''),
//  Recyclable('TROPHY', '', instTrash, ''),
//  Recyclable('UMBRELLA', '', instTrash, ''),
//  Recyclable('USB FLASH DRIVE', '', '', '', '', ''),
//  //TODO: CUTLERY라고 쳐도 나옴. 이거 걍 하나로 모으는 게 좋을듯. 어차피 TRASH.
//  Recyclable('UTENCIL', '(CERAMIC)', instTrash, ''),
//  Recyclable('UTENCIL', '(PLASTIC)', instTrash, ''),
//  Recyclable('UTENCIL', '(WOOD)', instTrash, ''),
//  Recyclable('VACUUM', '', instHouseholdBulkyWaste, ''),
//  Recyclable('VCR PLAYER', '', instElectronicWaste, ''),
//  Recyclable('WATER BOTTLE', '(PLASTIC)', instRecyclable, ''),
//  Recyclable('WATER FILTER', '', instTrash, ''),
//  Recyclable('WAX PAPER', '', instTrash, ''),
//  Recyclable('WRAPPING PAPER', '', instRecyclable, ''),
//  Recyclable('YOGURT', '', instTrash, ''),
//  //TODO: Add a photo.
//  Recyclable('Zipper Storage Bag', '', instTrash, ''),
];
