name: recycling_tracker_ver_2
description: A newly-designed recycling tracker with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  camera: ^0.5.8+2 #camera

  google_maps_flutter: ^0.5.29 #google map
  geolocator: ^5.3.2+2 #location service
  provider: ^4.3.2
  url_launcher: ^5.5.0 #show google map directions
  http: ^0.12.2 #http
  flutter_rating_bar: ^3.0.1+1 #five star/face rating bar

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Regular.ttf
        - asset: fonts/Rajdhani-Bold.ttf
          weight: 700